In [1]:
import numpy as np
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
import numpy as np
arr = np.full((2,3),9)
print(arr)

[[9 9 9]
 [9 9 9]]


In [3]:
import numpy as np
arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(0,5,2)
print(arr2)

[0 1 2 3 4]
[0 2 4]


In [4]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
import numpy as np
arr = np.random.random((2,3))
print(arr)

[[0.03045063 0.18927965 0.30771366]
 [0.05333116 0.54181317 0.60285531]]


In [10]:
import numpy as np
arr = np.arange(5)
print(arr)

condition = arr < 3
out = np.where(condition, arr, arr * 2)

print(condition)
print(out)

[0 1 2 3 4]
[ True  True  True False False]
[0 1 2 6 8]


In [12]:
import numpy as np
arr = np.array([[2,3], [3,4]])
out = arr.flatten()
print(arr)
print(out)

[[2 3]
 [3 4]]
[2 3 3 4]


In [13]:
import numpy as np

l = [[1,2,3],
     [4,5,6]]

data = np.array(l)
print(data)
print(data.shape)

data_rs = np.reshape(data, (3,2))
print(data_rs)
print(data_rs.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [14]:
import numpy as np

a_arr = np.array([[1,2,3],
                  [5,6,7]])

b_arr = a_arr[:, 1:3]
print(a_arr)
print(b_arr)

[[1 2 3]
 [5 6 7]]
[[2 3]
 [6 7]]


In [15]:
import numpy as np

a_arr = np.array([[1,2,3],
                  [5,6,7]])
print(a_arr)

b_arr = a_arr[:, 1:3]
print(b_arr)

print(a_arr[0,1])
b_arr[0,0] = 99
print(a_arr[0,1])

[[1 2 3]
 [5 6 7]]
[[2 3]
 [6 7]]
2
99


In [16]:
import numpy as np

arr = np.array([[1,2,3],
                [5,6,7],
                [9,10,11]])

row_m1 = arr[1, :]
row_m2 = arr[1:2, :]

print(row_m1, row_m1.shape)
print(row_m2, row_m2.shape)

[5 6 7] (3,)
[[5 6 7]] (1, 3)


In [17]:
import numpy as np

arr = np.array([[1,2,3],
                [5,6,7],
                [9,10,11]])

col_m1 = arr[:, 1]
col_m2 = arr[:, 1:2]

print(col_m1, col_m1.shape)
print(col_m2, col_m2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [18]:
import numpy as np

arr = np.array([[1,2,3],
                [5,6,7],
                [9,10,11]])

out1 = arr[[0,1,2],[0,1,0]]
print(out1)
out2 = arr [[0,0],[1,1]]
print(out2)

[1 6 9]
[2 2]


In [19]:
import numpy as np

arr = np.array([[1,2,3],
                [5,6,7],
                [9,10,11]])
print(arr)

bool_idx = (arr >2)
print(bool_idx)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[False False  True]
 [ True  True  True]
 [ True  True  True]]


In [20]:
import numpy as np

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(x)
print(y)

print(x+y)
print(np.add(x,y))

[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]
[ 6  8 10 12]


In [21]:
import numpy as np

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(x)
print(y)

print(x-y)
print(np.subtract(x,y))

[1 2 3 4]
[5 6 7 8]
[-4 -4 -4 -4]
[-4 -4 -4 -4]


In [22]:
import numpy as np

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(x)
print(y)

print(x*y)
print(np.multiply(x,y))

[1 2 3 4]
[5 6 7 8]
[ 5 12 21 32]
[ 5 12 21 32]


In [23]:
import numpy as np

x = np.array([5,6,7,8])
y = np.array([1,2,3,4])

print(x)
print(y)
#chia cac tung phan tuong ung x cho y
print(x/y)
print(x//y)
print(np.divide(x,y))

[5 6 7 8]
[1 2 3 4]
[5.         3.         2.33333333 2.        ]
[5 3 2 2]
[5.         3.         2.33333333 2.        ]


In [24]:
import numpy as np

x = np.array([5,6,7,8])
print(x)
print('can bac 2', np.sqrt(x))

[5 6 7 8]
can bac 2 [2.23606798 2.44948974 2.64575131 2.82842712]


In [25]:
import numpy as np

v = np.array([1,2])
w = np.array([2,3])
#tinh inner product
print(v.dot(w))
print(np.dot(v,w))

8
8


In [26]:
import numpy as np
v = np.array([[1,2],[3,4]])
w = np.array([2,3])


print(v)
print(w)

print(v.dot(w))
print(w.dot(v))

[[1 2]
 [3 4]]
[2 3]
[ 8 18]
[11 16]


In [27]:
import numpy as np

x = np.array([[1,2],
              [3,4]])
y = np.array([[2,3],
              [2,1]])

#nhan giua 2 ma tran
print(x.dot(y))
print(y.dot(x))

[[ 6  5]
 [14 13]]
[[11 16]
 [ 5  8]]


In [28]:
import numpy as np

x = np.array([[1,2],
              [3,4]])
#chuyen vi
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [29]:
import numpy as np

x = np.array([[1,2],
              [3,4]])

#tong cac phan tu cua mang
print(np.sum(x))

#tong tung cot
print(np.sum(x, axis = 0))

#tong tung dong
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [30]:
import numpy as np

data = np.array([1,2,3])

print(data.min())
print(data.max())

1
3


In [31]:
import numpy as np

data = np.array([1,2,3])
factor = 2

#broadcasting
result_multiplication = data*factor
result_minus = data - factor

print(data)
print(result_multiplication)
print(result_minus)

[1 2 3]
[2 4 6]
[-1  0  1]


In [32]:
import numpy as np

x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
v = np.array([1,0,1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
